language: ruby
cache: bundler
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  matrix:
    # - BUILD=buildPDF.sh
    - BUILD=buildPages.sh
     - BUILD=buildBluemix.sh
    - BUILD=buildElastic.sh
script: ./build/$BUILD
branches:
  only:
  - analytics-poc      
  - master
rvm:
- 2.1.2 # version of `ruby'
git:
  depth: 3
