language: ruby
cache: bundler
script:
  # - "./buildPages.sh" # execute this script on each commit
  # - "./buildBluemix.sh" # execute this script on each commit
  - "./buildPDF.sh" # execute this script on each commit
branches:
  only:
  - master # only take into account `master' branch
rvm:
- 2.2.2 # version of `ruby'
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
