language: ruby
cache: bundler
env:
  -BUILD=buildPDF.sh
  -BUILD=buildPages.sh
  -BUILD=buildBluemix.sh
script:
  # - "./buildPages.sh" # execute this script on each commit
  # - "./buildBluemix.sh" # execute this script on each commit
  # - "./buildPDF.sh" # execute this script on each commit
  - echo $BUILD
  - ./$BUILD
branches:
  only:
  - master # only take into account `master' branch
rvm:
- 2.1.2 # version of `ruby'
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
