name: "IBM MobileFirst Foundation Developer Center"
description: "Develop, test, manage, and secure your native and hybrid apps"
url: https://mobilefirstplatform.ibmcloud.com
source_url: https://github.ibm.com/MFPSamples/DevCenter
permalink: pretty
paginate: 10
paginate_path: "/blog/:num/"
markdown: kramdown
generate_redirects: false
print_pdf: false
# redcarpet:
#     extensions: ["with_toc_data", "tables"]
kramdown:
  input: GFM
  hard_wrap: false    
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
      layout: blogpost
      show_disqus: true
      pinned: false
      indexed: true
  -
    scope:
      path: "blog/rss"
    values:
      indexed: false
  -
    scope:
      path: "feed.xml"
    values:
      indexed: false
  -
    scope:
      path: "js"
    values:
      indexed: false
  -
    scope:
      path: "css"
    values:
      indexed: false
  -
    scope:
      path: ""
      type: "pages"
    values:
      category: page
      indexed: true
  -
    scope:
      path: "tutorials"
    values:
      layout: tutorial
      category: tutorial
      show_breadcrumb: true
      show_disqus: true
      show_in_nav: true
      print_pdf: true
  -
    scope:
      path: "labs"
    values:
      layout: labs
      show_disqus: true
      category: lab
  -
    scope:
      path: "pdf"
    values:
      layout: pdflist
      permalink: /:path/:basename:output_ext
      indexed: false
