name: "IBM MobileFirst Platform"
description: "Develop, test, manage, and secure your mobile web, native and hybrid apps"
url: https://developer.ibm.com
permalink: pretty
paginate: 10
paginate_path: "/blog/:num/"
markdown: redcarpet
generate_redirects: true
print_pdf: false
redcarpet:
    extensions: ["with_toc_data", "tables"]
gems:
  - jekyll-feed
  - jekyll-paginate
sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
      layout: blogpost
      show_disqus: true
  -
    scope:
      path: "tutorials"
    values:
      layout: tutorial
      show_breadcrumb: true
      show_disqus: true
      print_pdf: true
  -
    scope:
      path: "labs"
    values:
      layout: labs
      show_disqus: true
  -
    scope:
      path: "pdf"
    values:
      layout: pdflist
      permalink: /:path/:basename:output_ext