permalink: pretty
exclude: [old-backup]
gems:
  - jekyll-redirect-from
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
      layout: blogpost
  -
    scope:
      path: "tutorials"
    values:
      layout: tutorial
