name: "IBM MobileFirst Platform"
description: "Develop, test, manage, and secure your mobile web, native and hybrid apps"
url: https://developer.ibm.com
baseurl: /MFPSamples
permalink: pretty
exclude: [old-backup,tutorials]

gems:
  - jekyll-redirect-from
  - jekyll-feed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
      layout: blogpost
  -
    scope:
      path: "tutorials"
    values:
      layout: tutorial
      show_breadcrumb: true
  -
    scope:
      path: "product-integration"
    values:
      layout: tutorial
      show_breadcrumb: true
