baseurl: /NATHANH
permalink: pretty
exclude: [old-backup]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
  -
    scope:
      path: "tutorials"
    values:
      layout: tutorial  
