name: "IBM MobileFirst Platform"
description: "Develop, test, manage, and secure your mobile web, native and hybrid apps"
url: https://developer.ibm.com
baseurl: /MFPSamples
permalink: pretty
exclude: [old-backup]
#exclude: [old-backup,tutorials/en/foundation/6.3,tutorials/en/foundation/7.0,tutorials/en/foundation/7.1,tutorials/en/foundation/8.0,product-integration/7.0,product-integration/8.0]
gems:
  - jekyll-redirect-from
  - jekyll-feed
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
      layout: blogpost
  -
    scope:
      path: "tutorials"
    values:
      layout: tutorial
      show_breadcrumb: true
