name: "IBM MobileFirst Platform"
description: "Develop, test, manage, and secure your mobile web, native and hybrid apps"
url: https://developer.ibm.com
baseurl: /MFPSamples
permalink: pretty
paginate: 10
paginate_path: "/blog/:num/"
markdown: redcarpet
exclude: [vendor,build.sh,Gemfile,Gemfile.lock,README.md]

gems:
  - jekyll-feed
  - jekyll-paginate
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      category: blog
      layout: blogpost
      show_disqus: true
  -
    scope:
      path: "tutorials"
    values:
      layout: tutorial
      show_breadcrumb: true
      show_disqus: true
      print_pdf: false
  -
    scope:
      path: "labs"
    values:
      layout: labs
      show_disqus: true
